/**
 * Types for Promotion Team Agents
 * Following Interface Segregation Principle - granular interfaces
 */

import type { BaseMessage } from '@langchain/core/messages'

// Agent roles in the promotion team
export type AgentRole = 'manager' | 'salesperson' | 'evaluator'

// Salesperson writing styles for differentiated email content
export enum SalespersonStyle {
  /**
   * 理性说服风格：
   * - 强调产品功能、性价比、数据支撑
   * - 使用逻辑论证和事实陈述
   * - 适合注重实用性的用户
   */
  RATIONAL = 'rational',

  /**
   * 情感共鸣风格：
   * - 讲述品牌故事、用户体验
   * - 使用感性语言和场景描绘
   * - 适合追求生活品质的用户
   */
  EMOTIONAL = 'emotional',
}

// Product information for promotion emails
export interface ProductInfo {
  id: string
  name: string
  description: string
  price: number
  originalPrice?: number
  discount?: string
  category: string
  tags: string[]
  features?: string[]
  productUrl: string
  imageUrl: string
}

// Promotion strategy defined by manager
export interface PromotionStrategy {
  targetAudience: string
  keySellingPoints: string[]
  tone: string
  callToAction: string
  urgencyMessage?: string
}

// Email content generated by salesperson
export interface EmailDraft {
  subject: string
  bodyMarkdown: string
  style: SalespersonStyle
  salespersonId: string
}

// Individual draft evaluation (per salesperson)
export interface DraftEvaluation {
  salespersonId: string
  approved: boolean
  score: number
  feedback?: string
}

// Evaluation result from evaluator
export interface EvaluationResult {
  approved: boolean
  selectedDraft?: EmailDraft
  draftEvaluations?: DraftEvaluation[] // Per-draft pass/fail results
  htmlContent?: string
  feedback?: string
  issues?: {
    contentIssues?: string[]
    formatIssues?: string[]
  }
}

// Manager review result
export interface ManagerReviewResult {
  approved: boolean
  feedback?: string
  requiresContentRevision: boolean
  requiresFormatRevision: boolean
}

// Email sending result (from agent perspective)
export interface AgentEmailSendResult {
  success: boolean
  sentCount: number
  failedEmails?: string[]
  htmlContent: string
}

// Phase tracking for the workflow
export enum WorkflowPhase {
  STRATEGY = 'strategy',
  DRAFTING = 'drafting',
  EVALUATION = 'evaluation',
  MANAGER_REVIEW = 'manager_review',
  SENDING = 'sending',
  COMPLETED = 'completed',
}

// Configuration for agent creation
export interface AgentConfig {
  role: AgentRole
  systemPrompt: string
  temperature?: number
}

// Salesperson-specific configuration
export interface SalespersonConfig extends AgentConfig {
  role: 'salesperson'
  style: SalespersonStyle
  salespersonId: string
}

// Main workflow input
export interface PromotionWorkflowInput {
  product: ProductInfo
  customerEmails: string[]
}

// Workflow state messages wrapper
export interface WorkflowMessages {
  messages: BaseMessage[]
}
